## Stage 1 (Build)
FROM nginx:alpine as build
WORKDIR /app
COPY package.json ./

RUN apk add
RUN apk add --update nodejs nodejs-npm

RUN npm install -g @angular/cli
RUN npm install
COPY . ./

RUN ng --version
RUN ng build

## Stage 2 (Setup)
FROM nginx:alpine as runtime
COPY nginx.conf /etc/nginx/nginx.conf
WORKDIR /usr/share/nginx/html
COPY --from=build /app/dist/VstsDashboard .